import type { ExpertiseTag } from "./schema.ts";

export const EXPERTISE: ExpertiseTag[] = [
  {
    id: "biryani",
    label: "Biryani",
    emoji: "🍛",
    group: "cuisine",
  },
  {
    id: "dum-cooking",
    label: "Dum cooking",
    emoji: "🫕",
    group: "cuisine",
  },
  {
    id: "kachche-gosht",
    label: "Kachche gosht",
    emoji: "🥩",
    group: "cuisine",
  },
  {
    id: "haleem",
    label: "Haleem",
    emoji: "🥣",
    group: "cuisine",
  },
  {
    id: "south-indian",
    label: "South Indian",
    emoji: "🥞",
    group: "cuisine",
  },
  {
    id: "pastrami",
    label: "Pastrami",
    emoji: "🥪",
    group: "cuisine",
  },
  {
    id: "bagel-culture",
    label: "Bagels",
    emoji: "🥯",
    group: "cuisine",
  },
  {
    id: "parsi-cuisine",
    label: "Parsi cuisine",
    emoji: "🍮",
    group: "cuisine",
  },
  {
    id: "street-food",
    label: "Street food",
    emoji: "🥡",
    group: "cuisine",
  },
  {
    id: "hawker-food",
    label: "Hawker food",
    emoji: "🍜",
    group: "cuisine",
  },
  {
    id: "chicken-rice",
    label: "Chicken rice",
    emoji: "🍚",
    group: "cuisine",
  },
  {
    id: "laksa",
    label: "Laksa",
    emoji: "🍝",
    group: "cuisine",
  },
  {
    id: "kaya-toast",
    label: "Kaya toast",
    emoji: "🍞",
    group: "cuisine",
  },
  {
    id: "fish-and-chips",
    label: "Fish & chips",
    emoji: "🐟",
    group: "cuisine",
  },
  {
    id: "irani-chai",
    label: "Irani chai",
    emoji: "🫖",
    group: "drink",
  },
  {
    id: "cutting-chai",
    label: "Cutting chai",
    emoji: "🍵",
    group: "drink",
  },
  {
    id: "filter-coffee",
    label: "Filter coffee",
    emoji: "☕",
    group: "drink",
  },
  {
    id: "flat-white",
    label: "Flat white",
    emoji: "☕",
    group: "drink",
  },
  {
    id: "kopi-codes",
    label: "Kopi codes",
    emoji: "☕",
    group: "drink",
  },
  {
    id: "arabic-coffee",
    label: "Gahwa",
    emoji: "☕",
    group: "drink",
  },
  {
    id: "craft-beer",
    label: "Craft beer",
    emoji: "🍺",
    group: "drink",
  },
  {
    id: "third-wave",
    label: "Third-wave",
    emoji: "🫘",
    group: "drink",
  },
  {
    id: "hyderabadi-urdu",
    label: "Hyderabadi Urdu",
    emoji: "🗣️",
    group: "language",
  },
  {
    id: "bombay-tapori",
    label: "Tapori Hindi",
    emoji: "🗣️",
    group: "language",
  },
  {
    id: "kannada",
    label: "Kannada",
    emoji: "🗣️",
    group: "language",
  },
  {
    id: "singlish",
    label: "Singlish",
    emoji: "🗣️",
    group: "language",
  },
  {
    id: "aussie-slang",
    label: "Aussie slang",
    emoji: "🗣️",
    group: "language",
  },
  {
    id: "nyc-slang",
    label: "NYC slang",
    emoji: "🗣️",
    group: "language",
  },
  {
    id: "gulf-arabic",
    label: "Gulf Arabic",
    emoji: "🗣️",
    group: "language",
  },
  {
    id: "gulf-hospitality",
    label: "Gulf hospitality",
    emoji: "🕌",
    group: "culture",
  },
  {
    id: "bedouin-lore",
    label: "Bedouin lore",
    emoji: "🐪",
    group: "culture",
  },
  {
    id: "parsi-history",
    label: "Parsi history",
    emoji: "📜",
    group: "culture",
  },
  {
    id: "nyc-delis",
    label: "NYC delis",
    emoji: "🏙️",
    group: "culture",
  },
  {
    id: "bodega-culture",
    label: "Bodega culture",
    emoji: "🏪",
    group: "culture",
  },
  {
    id: "bombay-lore",
    label: "Bombay lore",
    emoji: "🌇",
    group: "culture",
  },
  {
    id: "ramzan-iftar",
    label: "Ramzan & iftar",
    emoji: "🌙",
    group: "culture",
  },
  {
    id: "chope-culture",
    label: "Chope culture",
    emoji: "🪑",
    group: "culture",
  },
  {
    id: "kopitiam",
    label: "Kopitiam",
    emoji: "🏪",
    group: "culture",
  },
  {
    id: "bondi-surf",
    label: "Bondi surf",
    emoji: "🏄",
    group: "culture",
  },
  {
    id: "surf-culture",
    label: "Surf culture",
    emoji: "🌊",
    group: "culture",
  },
  {
    id: "gold-trading",
    label: "Gold trading",
    emoji: "🪙",
    group: "skill",
  },
  {
    id: "karat-testing",
    label: "Karat testing",
    emoji: "⚖️",
    group: "skill",
  },
  {
    id: "tech-bengaluru",
    label: "Bengaluru tech",
    emoji: "💻",
    group: "skill",
  },
  {
    id: "philosophy",
    label: "Philosophy",
    emoji: "💭",
    group: "skill",
  },
  {
    id: "stars-navigation",
    label: "Stars & night sky",
    emoji: "🌌",
    group: "skill",
  },
  {
    id: "story-telling",
    label: "Storytelling",
    emoji: "📖",
    group: "skill",
  },
  {
    id: "cricket",
    label: "Cricket",
    emoji: "🏏",
    group: "sport",
  },
  {
    id: "chess",
    label: "Chess",
    emoji: "♟️",
    group: "sport",
  },
  {
    id: "indie-music",
    label: "Indie music",
    emoji: "🎸",
    group: "music",
  },
  {
    id: "jazz-nyc",
    label: "NYC jazz",
    emoji: "🎷",
    group: "music",
  },
  {
    id: "qawwali",
    label: "Qawwali",
    emoji: "🎶",
    group: "music",
  },
  {
    id: "oud",
    label: "Oud",
    emoji: "🎵",
    group: "music",
  },
  {
    id: "hip-hop",
    label: "Hip-hop",
    emoji: "🎤",
    group: "music",
  },
  {
    id: "local-trains",
    label: "Local trains",
    emoji: "🚉",
    group: "culture",
  },
  {
    id: "lower-east-side",
    label: "Lower East Side",
    emoji: "🗽",
    group: "culture",
  },
  {
    id: "political-banter",
    label: "Political banter",
    emoji: "🗞️",
    group: "culture",
  },
  {
    id: "poetry",
    label: "Poetry",
    emoji: "📝",
    group: "culture",
  },
  {
    id: "pickling",
    label: "Pickling",
    emoji: "🥒",
    group: "cuisine",
  },
  {
    id: "hokkien",
    label: "Hokkien",
    emoji: "🗣️",
    group: "language",
  },
  {
    id: "espresso-science",
    label: "Espresso science",
    emoji: "🧪",
    group: "skill",
  },
  {
    id: "coffee-craft",
    label: "Coffee craft",
    emoji: "☕",
    group: "skill",
  },
];
