/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Animated Woman.glb -o src/components/AnimatedWoman.jsx -r public
*/

import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { atom, useAtom } from "jotai";
import React, { useEffect, useMemo, useRef, useState, memo, useCallback } from "react";
import { SkeletonUtils } from "three-stdlib";
import { useGrid } from "../hooks/useGrid";
import { socket, userAtom, avatarDispatch, bondsAtom, charactersAtom, characterEmotionsAtom, dmInboxOpenAtom, selfLivePosition, mapAtom, profileViewTargetAtom } from "./SocketManager";
import { dmPanelTargetAtom } from "./DirectMessagePanel";
import soundManager from "../audio/SoundManager";

import * as THREE from "three";
import { GLTFLoader } from "three-stdlib";
import { motion } from "framer-motion-3d";

// Atom to track which character's profile popup is open
export const selectedCharacterAtom = atom(null);
export const followedCharacterAtom = atom(null);

const MOVEMENT_SPEED = 4;
// How fast the character rotates to face movement direction (radians/sec)
const ROTATION_SPEED = 12;
// Arrival threshold — snap to waypoint when this close
const ARRIVAL_THRESHOLD = 0.1;

// Distance threshold (squared) for rendering avatars — avatars beyond this are culled
const RENDER_DISTANCE_SQ = 30 * 30;
// Hysteresis: use a slightly larger radius before re-culling to prevent flicker
const RENDER_DISTANCE_HIDE_SQ = 33 * 33;

// Distance tier thresholds with hysteresis to prevent animation throttle flicker
const NEAR_ENTER_SQ = 15 * 15;
const NEAR_EXIT_SQ = 17 * 17;
const MID_ENTER_SQ = RENDER_DISTANCE_SQ;
const MID_EXIT_SQ = RENDER_DISTANCE_HIDE_SQ;

// Reusable vectors to avoid allocations in the hot loop
const _direction = new THREE.Vector3();
const _targetQuat = new THREE.Quaternion();
const _idleGlanceQuat = new THREE.Quaternion();
const _lookMatrix = new THREE.Matrix4();
const _up = new THREE.Vector3(0, 1, 0);
const _zero = new THREE.Vector3();
const _tmpWorldPos = new THREE.Vector3();
const _tmpLocalPos = new THREE.Vector3();
const _tmpQuat = new THREE.Quaternion();
// Pre-computed quaternions for sitting pose.
// NOTE: Some rigs have mirrored local axes between left/right leg bones, so we keep
// both +90 and -90 variants and apply them per-leg.
const _thighSitQuatNeg = new THREE.Quaternion()
  .setFromAxisAngle(new THREE.Vector3(1, 0, 0), -Math.PI / 2);
const _thighSitQuatPos = new THREE.Quaternion()
  .setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2);
// Shin (Leg): bend knee 90° around local X
const _kneeBendPos = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2);
const _kneeBendNeg = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1, 0, 0), -Math.PI / 2);

const EMOTION_EMOJIS = {
  happy: "\u{1F604}",
  sad: "\u{1F622}",
  angry: "\u{1F620}",
  love: "\u{1F970}",
  surprised: "\u{1F62E}",
  anxious: "\u{1F630}",
  disgusted: "\u{1F922}",
  neutral: "\u{1F642}",
  playful: "\u{1F61C}",
  confident: "\u{1F60E}",
};

// Non-humanoid model configurations — maps bone names for procedural animation
const MODEL_CONFIGS = {
  nubcat: {
    test: (url) => url.includes("sillyNubCat"),
    bones: {
      body: "body_00",
      pawR: "paw.R_01",
      pawL: "paw.L_02",
      legR: "leg.R_03",
      legL: "leg.L_04",
      cheekR: "cheek.R_05",
      cheekL: "cheek.L_06",
      head: "head_07",
    },
  },
};

export function getModelConfig(url) {
  for (const config of Object.values(MODEL_CONFIGS)) {
    if (config.test(url)) return config;
  }
  return null;
}

// Reusable quaternion/euler for procedural bone offsets
const _procQuat = new THREE.Quaternion();
const _procEuler = new THREE.Euler();

/**
 * Apply procedural bone animation for non-humanoid models.
 * Resets bones to rest pose, then applies sine-wave-driven rotations.
 */
export function applyProceduralAnimation(state, time, bones, restPoses) {
  if (!bones || !restPoses) return;

  // Reset all bones to rest pose
  for (const key in bones) {
    if (bones[key] && restPoses[key]) {
      bones[key].quaternion.copy(restPoses[key]);
    }
  }

  // Apply rotation offset relative to rest pose
  const offset = (key, rx, ry, rz) => {
    const bone = bones[key];
    if (!bone || !restPoses[key]) return;
    _procQuat.setFromEuler(_procEuler.set(rx, ry, rz));
    bone.quaternion.multiply(_procQuat);
  };

  // body_00 has 90° X rest rotation, paws have ~90° Z rest rotations,
  // legs have ~180° Z rest rotation. Offsets are in each bone's local space.
  // For this rig: body Y = world forward, paw/leg Y = swing axis.
  switch (state) {
    case "walk": {
      const t = time * 8;
      const s = Math.sin(t);
      // Body side-to-side waddle + slight forward bob
      offset("body", s * 0.08, 0, Math.sin(t * 2) * 0.05);
      // Front paws paddle alternating
      offset("pawR", 0, s * 0.4, 0);
      offset("pawL", 0, -s * 0.4, 0);
      // Back legs waddle opposite to body sway
      offset("legR", 0, -s * 0.35, 0);
      offset("legL", 0, s * 0.35, 0);
      // Head bobs side to side with body + slight nod
      offset("head", s * 0.06, 0, Math.sin(t * 2) * 0.04);
      // Cheeks jiggle with the waddle
      offset("cheekR", 0, Math.abs(s) * 0.06, 0);
      offset("cheekL", 0, Math.abs(s) * 0.06, 0);
      break;
    }
    case "idle": {
      const t = time * 2;
      offset("body", 0, 0, Math.sin(t) * 0.015);
      offset("head", Math.sin(t * 0.5) * 0.06, Math.sin(t * 0.3) * 0.04, 0);
      break;
    }
    case "dance": {
      const t = time * 6;
      // Bouncy body
      offset("body", 0, 0, Math.abs(Math.sin(t * 2)) * 0.08);
      offset("body", Math.sin(t) * 0.12, 0, 0);
      // Exaggerated paw alternation
      offset("pawR", 0, Math.sin(t) * 0.7, 0);
      offset("pawL", 0, Math.sin(t + Math.PI) * 0.7, 0);
      // Back legs bounce
      offset("legR", 0, Math.sin(t * 0.5) * 0.4, 0);
      offset("legL", 0, Math.sin(t * 0.5 + Math.PI) * 0.4, 0);
      // Head wobble
      offset("head", Math.sin(t * 2) * 0.2, 0, Math.sin(t) * 0.15);
      // Cheek puff
      offset("cheekR", 0, Math.sin(t * 3) * 0.12, 0);
      offset("cheekL", 0, Math.sin(t * 3 + Math.PI) * 0.12, 0);
      break;
    }
    case "wave": {
      const t = time * 3;
      offset("head", Math.sin(t * 0.7) * 0.15, 0, Math.sin(t) * 0.2);
      offset("body", 0, 0, Math.sin(t * 0.5) * 0.04);
      offset("pawR", 0, 0, Math.sin(t * 2) * 0.4);
      offset("cheekR", 0, Math.sin(t * 2) * 0.15, 0);
      offset("cheekL", 0, Math.sin(t * 2 + Math.PI) * 0.15, 0);
      break;
    }
    case "sit": {
      // Lower the body forward
      offset("body", 0, 0, 0.15);
      // Tuck back legs
      offset("legR", 0, -0.4, 0);
      offset("legL", 0, -0.4, 0);
      // Slight paw tuck
      offset("pawR", 0, -0.1, 0);
      offset("pawL", 0, -0.1, 0);
      // Subtle idle while sitting
      const t = time * 1.5;
      offset("head", Math.sin(t) * 0.06, Math.sin(t * 0.6) * 0.04, 0);
      break;
    }
  }
}

export const Avatar = memo(function Avatar({
  id,
  userId,
  avatarUrl = "/models/sillyNubCat.glb",
  name = "Player",
  isBot = false,
  leaving = false,
  gridPosition,
  showHtmlOverlay = true,
}) {
  const [chatMessage, setChatMessage] = useState("");
  const [actionStatus, setActionStatus] = useState(null); // { action, detail }
  const [showBondHearts, setShowBondHearts] = useState(false);
  const [bondEmote, setBondEmote] = useState(null); // "highfive" | "hug" | null
  const [, setSelectedCharacter] = useAtom(selectedCharacterAtom);
  const [followedCharacter, setFollowedCharacter] = useAtom(followedCharacterAtom);
  const [, setProfileViewTarget] = useAtom(profileViewTargetAtom);
  const { gridToVector3 } = useGrid();
  const position = useMemo(() => gridToVector3(gridPosition), []);
  // Use refs for culling state to avoid re-renders from useFrame distance checks
  const isNearbyRef = useRef(true);
  const distanceTierRef = useRef("near"); // "near" (<15u), "mid" (15-30u), "far" (>30u)
  const midAnimAccRef = useRef(0);

  const avatar = useRef();
  const hipsRef = useRef(null);
  const leftUpLegRef = useRef(null);
  const rightUpLegRef = useRef(null);
  const leftLegRef = useRef(null);
  const rightLegRef = useRef(null);
  const leftUpLegRestRef = useRef(null);
  const rightUpLegRestRef = useRef(null);
  const leftLegRestRef = useRef(null);
  const rightLegRestRef = useRef(null);
  const sitLegFixRef = useRef(null);
  const pathRef = useRef([]);
  const pathIndexRef = useRef(0); // index pointer instead of shift()

  // When the server sends a new position (e.g. after reconnect), snap to it
  const lastServerGridPos = useRef(gridPosition);
  useEffect(() => {
    if (
      group.current &&
      gridPosition &&
      (gridPosition[0] !== lastServerGridPos.current?.[0] ||
        gridPosition[1] !== lastServerGridPos.current?.[1])
    ) {
      const newPos = gridToVector3(gridPosition);
      group.current.position.copy(newPos);
      // Clear any stale path so the avatar doesn't walk from old position
      pathRef.current = [];
      pathIndexRef.current = 0;
    }
    lastServerGridPos.current = gridPosition;
  }, [gridPosition]);

  const group = useRef();
  const { scene } = useGLTF(avatarUrl);
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // Task 7: Share GPU geometry buffers — only 4 unique avatar URLs exist
  useMemo(() => {
    const origMeshes = [];
    scene.traverse((child) => {
      if (child.isMesh) origMeshes.push(child);
    });
    let i = 0;
    clone.traverse((child) => {
      if (child.isMesh && i < origMeshes.length) {
        child.geometry = origMeshes[i].geometry; // share GPU buffer
        i++;
      }
    });
  }, [clone, scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);

  // Detect non-humanoid model type for procedural animation
  const modelConfig = useMemo(() => getModelConfig(avatarUrl), [avatarUrl]);
  const isNonHumanoid = !!modelConfig;
  const isNubcat = useMemo(() => avatarUrl.includes("sillyNubCat"), [avatarUrl]);
  const proceduralBonesRef = useRef(null);
  const restPosesRef = useRef(null);
  const proceduralTimeRef = useRef(0);

  const { animations: walkAnimation } = useGLTF("/animations/M_Walk_001.glb");
  const { animations: danceAnimation } = useGLTF(
    "/animations/M_Dances_001.glb"
  );
  const { animations: idleAnimation } = useGLTF(
    "/animations/M_Standing_Idle_001.glb"
  );
  const { animations: waveAnimation } = useGLTF(
    "/animations/M_Standing_Expressions_001.glb"
  );
  const { animations: sitAnimation } = useGLTF(
    "/animations/M_Sitting_001.glb"
  );

  // Remove all leg tracks from sitting animation — the animation has incorrect
  // leg rotation values for this rig. We override leg pose manually in useFrame.
  const fixedSitClip = useMemo(() => {
    const clip = sitAnimation[0].clone();
    clip.tracks = clip.tracks.filter(
      (track) =>
        !track.name.startsWith("LeftUpLeg.") &&
        !track.name.startsWith("RightUpLeg.") &&
        !track.name.startsWith("LeftLeg.") &&
        !track.name.startsWith("RightLeg.")
    );
    return clip;
  }, [sitAnimation]);

  const { actions, mixer } = useAnimations(
    isNonHumanoid ? [] : [walkAnimation[0], idleAnimation[0], danceAnimation[0], waveAnimation[0], fixedSitClip],
    avatar
  );

  // Use refs for animation state to avoid re-renders from useFrame
  const animationRef = useRef("M_Standing_Idle_001");
  const isDancingRef = useRef(false);
  const isWavingRef = useRef(false);
  const isSittingRef = useRef(false);
  const walkToSitRef = useRef(false);
  const seatDataRef = useRef(null); // { seatPos, seatHeight, seatRotation }
  const waveTargetIdRef = useRef(null);
  const waveTimeoutRef = useRef(null);
  const initRef = useRef(false);
  // Random offset so characters don't animate in lockstep
  const animOffsetRef = useRef(Math.random());
  // Random initial facing direction so characters don't all face the same way
  const initialRotationRef = useRef(Math.random() * Math.PI * 2);
  // Footstep sound accumulator (local player only)
  const footstepAccRef = useRef(0);
  const footstepVariantRef = useRef(0);
  // Grace period to avoid idle flash between path replacements
  const walkGraceRef = useRef(0);
  // Staggered entrance delay so characters pop in at different times
  const entranceDelayRef = useRef(0.05 + Math.random() * 0.5);
  // Fade-in/fade-out opacity tracking
  const opacityRef = useRef(0); // start at 0 for fade-in
  const fadeStartedRef = useRef(false); // delay fade-in until entrance delay elapses
  const fadeTimerRef = useRef(0);
  const leavingRef = useRef(false);
  useEffect(() => { leavingRef.current = leaving; }, [leaving]);
  // Cache mesh materials for efficient per-frame opacity updates
  const meshMaterialsRef = useRef([]);
  // Idle look-around state — characters periodically glance in different directions
  const idleLookTimerRef = useRef(2 + Math.random() * 5); // seconds until next look
  const idleLookTargetRef = useRef(null); // target quaternion for idle glance
  const idleTimeRef = useRef(0); // how long character has been idle
  const [showChatBubble, setShowChatBubble] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [isThinking, setIsThinking] = useState(false);
  const thinkingTimeoutRef = useRef(null);

  // Apply animation changes via ref — only triggers React state when animation actually changes
  const applyAnimation = useCallback((newAnim) => {
    if (animationRef.current === newAnim) return;
    const oldAnim = animationRef.current;
    animationRef.current = newAnim;
    if (actions[oldAnim]) actions[oldAnim].fadeOut(0.32);
    if (actions[newAnim]) {
      const action = actions[newAnim];
      action.reset().fadeIn(initRef.current ? 0.32 : 0).play();
      // Offset the starting time so characters aren't in sync
      const clip = action.getClip();
      if (clip) action.time = animOffsetRef.current * clip.duration;
      initRef.current = true;
    }
  }, [actions]);

  useEffect(() => {
    const materials = [];
    clone.traverse((child) => {
      if (child.isMesh) {
        child.castShadow = false;
        child.receiveShadow = true;
        // Clone material per-avatar so opacity changes don't leak to other instances
        if (child.material) {
          child.material = child.material.clone();
          child.material.transparent = true;
          child.material.depthWrite = true;
          child.material.opacity = 0;
          materials.push(child.material);
        }
      }
    });
    meshMaterialsRef.current = materials;
  }, [clone]);

  // Reset all cached refs when the model changes so animation state starts fresh
  useEffect(() => {
    hipsRef.current = null;
    leftUpLegRef.current = null;
    rightUpLegRef.current = null;
    leftLegRef.current = null;
    rightLegRef.current = null;
    leftUpLegRestRef.current = null;
    rightUpLegRestRef.current = null;
    leftLegRestRef.current = null;
    rightLegRestRef.current = null;
    sitLegFixRef.current = null;
    proceduralBonesRef.current = null;
    restPosesRef.current = null;
    proceduralTimeRef.current = 0;
    // Reset animation state so humanoid animations re-initialize properly.
    // Use empty string (not the idle animation name) so the next applyAnimation()
    // call from useFrame doesn't early-return thinking the animation is already active.
    animationRef.current = "";
    initRef.current = false;
    isDancingRef.current = false;
    isWavingRef.current = false;
    isSittingRef.current = false;
    walkToSitRef.current = false;
    seatDataRef.current = null;
  }, [clone]);

  // Initial animation play + random facing direction
  useEffect(() => {
    const anim = animationRef.current;
    if (actions[anim]) {
      const action = actions[anim];
      action.reset().fadeIn(0).play();
      // Offset so each character starts at a different point in the cycle
      const clip = action.getClip();
      if (clip) action.time = animOffsetRef.current * clip.duration;
      initRef.current = true;
    }
    // Apply random initial facing direction
    if (group.current) {
      group.current.quaternion.setFromAxisAngle(_up, initialRotationRef.current);
    }
  }, [actions, avatarUrl]);

  useEffect(() => {
    function onPlayerDance(value) {
      isDancingRef.current = true;
      isSittingRef.current = false;
      walkToSitRef.current = false;
      seatDataRef.current = null;
    }
    function onPlayerMove(value) {
      // Clear sitting state on any movement
      isSittingRef.current = false;
      walkToSitRef.current = false;
      seatDataRef.current = null;

      const newPath = [];
      value.path?.forEach((gridPosition) => {
        newPath.push(gridToVector3(gridPosition));
      });
      // If avatar is currently culled, skip path animation entirely —
      // just update server position so it snaps correctly when it becomes visible
      if (!isNearbyRef.current && id !== user) {
        pathRef.current = [];
        pathIndexRef.current = 0;
        if (value.path && value.path.length > 0) {
          lastServerGridPos.current = value.path[value.path.length - 1];
        }
        return;
      }

      // Skip leading waypoints that the character is already at/near
      // so we don't pause for a frame at the start of a new path
      let startIndex = 0;
      if (group.current && newPath.length > 1) {
        while (
          startIndex < newPath.length - 1 &&
          group.current.position.distanceTo(newPath[startIndex]) < ARRIVAL_THRESHOLD
        ) {
          startIndex++;
        }
      }

      pathRef.current = newPath;
      pathIndexRef.current = startIndex;
      if (value.path && value.path.length > 0) {
        lastServerGridPos.current = value.path[value.path.length - 1];
      }
    }

    let chatMessageBubbleTimeout;
    function onPlayerChatMessage(value) {
      setChatMessage(value.message);
      clearTimeout(chatMessageBubbleTimeout);
      setShowChatBubble(true);
      chatMessageBubbleTimeout = setTimeout(() => {
        setShowChatBubble(false);
      }, 5000);
    }

    function onPlayerAction(value) {
      if (value.action === null) {
        setActionStatus(null);
      } else {
        setActionStatus({ action: value.action, detail: value.detail });
      }
    }

    function onPlayerWaveAt(value) {
      waveTargetIdRef.current = value.targetId;
      isWavingRef.current = true;
      isDancingRef.current = false;
      isSittingRef.current = false;
      walkToSitRef.current = false;
      seatDataRef.current = null;
      pathRef.current = [];
      pathIndexRef.current = 0;
      clearTimeout(waveTimeoutRef.current);
      waveTimeoutRef.current = setTimeout(() => {
        isWavingRef.current = false;
        waveTargetIdRef.current = null;
      }, 3000);
    }

    function onPlayerSit(value) {
      // Set path from event data (character walks to sit spot)
      const newPath = [];
      value.path?.forEach((gridPosition) => {
        newPath.push(gridToVector3(gridPosition));
      });
      if (!isNearbyRef.current && id !== user) {
        // Culled avatar — snap to seat directly
        pathRef.current = [];
        pathIndexRef.current = 0;
        seatDataRef.current = {
          seatPos: value.seatPos,
          seatHeight: value.seatHeight,
          seatRotation: value.seatRotation,
        };
        isSittingRef.current = true;
        walkToSitRef.current = false;
        isDancingRef.current = false;
        isWavingRef.current = false;
        if (value.path && value.path.length > 0) {
          lastServerGridPos.current = value.path[value.path.length - 1];
        }
        return;
      }
      pathRef.current = newPath;
      pathIndexRef.current = 0;
      seatDataRef.current = {
        seatPos: value.seatPos,
        seatHeight: value.seatHeight,
        seatRotation: value.seatRotation,
      };
      walkToSitRef.current = true;
      isDancingRef.current = false;
      isWavingRef.current = false;
      if (value.path && value.path.length > 0) {
        lastServerGridPos.current = value.path[value.path.length - 1];
      }
    }

    function onPlayerUnsit() {
      isSittingRef.current = false;
      walkToSitRef.current = false;
      seatDataRef.current = null;
    }

    function onBondEmotePlay(value) {
      const emoteLabel = value.emote === "highfive" ? "\u{1F64F} Hi-Five!" : "\u{1FAC2} Hug!";
      setBondEmote(emoteLabel);
      setTimeout(() => setBondEmote(null), 3000);
    }

    function onPlayerThinking(value) {
      clearTimeout(thinkingTimeoutRef.current);
      if (value.thinking) {
        setIsThinking(true);
        // Auto-hide after 30 seconds if bot forgets to clear it
        thinkingTimeoutRef.current = setTimeout(() => {
          setIsThinking(false);
        }, 30000);
      } else {
        setIsThinking(false);
      }
    }

    // Register on dispatch maps — O(1) lookup, no per-avatar socket listener
    avatarDispatch.playerMove.set(id, onPlayerMove);
    avatarDispatch.playerDance.set(id, onPlayerDance);
    avatarDispatch.playerChatMessage.set(id, onPlayerChatMessage);
    avatarDispatch.playerAction.set(id, onPlayerAction);
    avatarDispatch.playerWaveAt.set(id, onPlayerWaveAt);
    avatarDispatch.playerSit.set(id, onPlayerSit);
    avatarDispatch.playerUnsit.set(id, onPlayerUnsit);
    avatarDispatch.bondEmotePlay.set(id, onBondEmotePlay);
    avatarDispatch.playerThinking.set(id, onPlayerThinking);

    return () => {
      avatarDispatch.playerMove.delete(id);
      avatarDispatch.playerDance.delete(id);
      avatarDispatch.playerChatMessage.delete(id);
      avatarDispatch.playerAction.delete(id);
      avatarDispatch.playerWaveAt.delete(id);
      avatarDispatch.playerSit.delete(id);
      avatarDispatch.playerUnsit.delete(id);
      avatarDispatch.bondEmotePlay.delete(id);
      avatarDispatch.playerThinking.delete(id);
      clearTimeout(chatMessageBubbleTimeout);
      clearTimeout(waveTimeoutRef.current);
      clearTimeout(thinkingTimeoutRef.current);
    };
  }, [id]);

  const [user] = useAtom(userAtom);
  const [bonds] = useAtom(bondsAtom);
  const [characters] = useAtom(charactersAtom);
  const [characterEmotions] = useAtom(characterEmotionsAtom);
  const [mapData] = useAtom(mapAtom);
  const bondsRef = useRef(bonds);
  const charactersRef = useRef(characters);
  const mapDataRef = useRef(mapData);
  useEffect(() => { bondsRef.current = bonds; }, [bonds]);
  useEffect(() => { charactersRef.current = characters; }, [characters]);
  useEffect(() => { mapDataRef.current = mapData; }, [mapData]);

  // Throttle visibility checks — only run every N frames
  const frameCountRef = useRef(0);

  useFrame(({ scene: threeScene }, delta) => {
    if (!avatar.current || !group.current) return;

    // Update shared live position ref for the local player (read by Minimap)
    if (id === user && group.current) {
      const gd = mapDataRef.current?.gridDivision || 1;
      selfLivePosition.current = [
        Math.floor(group.current.position.x * gd),
        Math.floor(group.current.position.z * gd),
      ];
    }

    // Distance-based culling — check every 15 frames
    frameCountRef.current++;
    if (frameCountRef.current % 15 === 0) {
      const character = threeScene.getObjectByName(`character-${user}`);
      if (character && group.current) {
        const dx = character.position.x - group.current.position.x;
        const dz = character.position.z - group.current.position.z;
        const distSq = dx * dx + dz * dz;
        // Hysteresis: use tighter threshold to show, wider to hide
        const newNearby = isNearbyRef.current
          ? distSq < RENDER_DISTANCE_HIDE_SQ
          : distSq < RENDER_DISTANCE_SQ;
        if (newNearby !== isNearbyRef.current) {
          isNearbyRef.current = newNearby;
          group.current.visible = newNearby || id === user;
          // When becoming visible after being culled, snap to last known server position
          // to prevent stale position artifacts
          if (newNearby && lastServerGridPos.current) {
            const snapPos = gridToVector3(lastServerGridPos.current);
            group.current.position.copy(snapPos);
            // Clear any stale path so avatar doesn't walk from wrong position
            pathRef.current = [];
            pathIndexRef.current = 0;
          }
        }
        // Update distance tier with hysteresis to prevent animation throttle flicker
        if (distanceTierRef.current === "near") {
          if (distSq >= NEAR_EXIT_SQ) {
            distanceTierRef.current = distSq < MID_EXIT_SQ ? "mid" : "far";
          }
        } else if (distanceTierRef.current === "mid") {
          if (distSq < NEAR_ENTER_SQ) {
            distanceTierRef.current = "near";
          } else if (distSq >= MID_EXIT_SQ) {
            distanceTierRef.current = "far";
          }
        } else {
          // "far"
          if (distSq < NEAR_ENTER_SQ) {
            distanceTierRef.current = "near";
          } else if (distSq < MID_ENTER_SQ) {
            distanceTierRef.current = "mid";
          }
        }
      } else if (!character && !isNearbyRef.current) {
        isNearbyRef.current = true;
        group.current.visible = true;
        distanceTierRef.current = "near";
      }
    }

    // Fade-in / fade-out opacity animation
    fadeTimerRef.current += delta;
    const isLeaving = leavingRef.current;
    if (isLeaving) {
      // Fade out over ~0.6s
      opacityRef.current = Math.max(0, opacityRef.current - delta * 1.7);
    } else if (fadeTimerRef.current > entranceDelayRef.current) {
      // Fade in over ~0.5s (starts after entrance delay)
      fadeStartedRef.current = true;
      opacityRef.current = Math.min(1, opacityRef.current + delta * 2.0);
    }
    if (fadeStartedRef.current || isLeaving) {
      const mats = meshMaterialsRef.current;
      const op = opacityRef.current;
      for (let i = 0; i < mats.length; i++) {
        mats[i].opacity = op;
      }
    }

    // Bond proximity hearts — check every 60 frames (~1s) for local player only
    if (id === user && frameCountRef.current % 60 === 0 && group.current) {
      const curBonds = bondsRef.current;
      const curChars = charactersRef.current;
      let nearBonded = false;
      if (curBonds && curChars) {
        for (const c of curChars) {
          if (c.id === user || !c.name) continue;
          const b = curBonds[c.name];
          if (!b || !b.maxLevel) continue;
          const other = threeScene.getObjectByName(`character-${c.id}`);
          if (!other) continue;
          const dx = group.current.position.x - other.position.x;
          const dz = group.current.position.z - other.position.z;
          if (dx * dx + dz * dz < 64) { nearBonded = true; break; }
        }
      }
      setShowBondHearts(nearBonded);
    }

    // Skip all movement/animation for non-visible distant avatars
    if (!isNearbyRef.current && id !== user) return;

    if (isNonHumanoid) {
      // Cache non-humanoid bone references on first access
      if (!proceduralBonesRef.current && modelConfig) {
        const bones = {};
        const rests = {};
        for (const [key, boneName] of Object.entries(modelConfig.bones)) {
          const bone = avatar.current.getObjectByName(boneName);
          if (bone) {
            bones[key] = bone;
            rests[key] = bone.quaternion.clone();
          }
        }
        proceduralBonesRef.current = bones;
        restPosesRef.current = rests;
      }
    }

    // Cache humanoid leg bones for sitting overrides on all models EXCEPT nubcat.
    // (nubcat uses the procedural rig with different bone names/orientation.)
    if (!isNubcat) {
      if (!hipsRef.current) {
        hipsRef.current = avatar.current.getObjectByName("Hips");
        leftUpLegRef.current = avatar.current.getObjectByName("LeftUpLeg");
        rightUpLegRef.current = avatar.current.getObjectByName("RightUpLeg");
        leftLegRef.current = avatar.current.getObjectByName("LeftLeg");
        rightLegRef.current = avatar.current.getObjectByName("RightLeg");

        // Cache rest pose rotations so our sit overrides are applied as deltas.
        if (leftUpLegRef.current && !leftUpLegRestRef.current) leftUpLegRestRef.current = leftUpLegRef.current.quaternion.clone();
        if (rightUpLegRef.current && !rightUpLegRestRef.current) rightUpLegRestRef.current = rightUpLegRef.current.quaternion.clone();
        if (leftLegRef.current && !leftLegRestRef.current) leftLegRestRef.current = leftLegRef.current.quaternion.clone();
        if (rightLegRef.current && !rightLegRestRef.current) rightLegRestRef.current = rightLegRef.current.quaternion.clone();
      }
      const hips = hipsRef.current;
      // Only reset hips X/Z drift when NOT sitting — standing/walking root motion fix
      if (hips && !isSittingRef.current) {
        const hx = hips.position.x;
        const hz = hips.position.z;
        if (Math.abs(hx) > 0.05 || Math.abs(hz) > 0.05) {
          hips.position.set(0, hips.position.y, 0);
        }
      }
    }

    // Handle sitting state — skip normal movement when seated
    if (isSittingRef.current && seatDataRef.current) {
      const seatWorldPos = gridToVector3(seatDataRef.current.seatPos);
      const rot = seatDataRef.current.seatRotation;
      group.current.position.set(seatWorldPos.x, seatDataRef.current.seatHeight, seatWorldPos.z);
      group.current.quaternion.setFromAxisAngle(_up, rot);
      group.current.updateMatrixWorld(true);
      applyAnimation("M_Sitting_001");
      // Override full leg rotation for all rigs that expose humanoid leg bones,
      // except nubcat (which uses a separate procedural rig).
      if (!isNubcat) {
        // Some rigs have the thigh axis mirrored, which makes the sit pose flip 180deg.
        // Pick the per-leg thigh sign that puts the knee forward in group-local +Z.
        if (!sitLegFixRef.current && group.current && avatar.current && leftUpLegRef.current && rightUpLegRef.current && leftLegRef.current && rightLegRef.current) {
          const leftFoot = avatar.current.getObjectByName("LeftFoot");
          const rightFoot = avatar.current.getObjectByName("RightFoot");

          const scoreKneeForwardZ = (upLeg, upLegRest, knee, thighDelta) => {
            if (upLegRest) _tmpQuat.copy(upLegRest).multiply(thighDelta);
            else _tmpQuat.copy(thighDelta);
            upLeg.quaternion.copy(_tmpQuat);
            avatar.current.updateMatrixWorld(true);
            knee.getWorldPosition(_tmpWorldPos);
            _tmpLocalPos.copy(_tmpWorldPos);
            group.current.worldToLocal(_tmpLocalPos);
            return _tmpLocalPos.z;
          };

          const pickThigh = (upLeg, upLegRest, knee) => {
            const zNeg = scoreKneeForwardZ(upLeg, upLegRest, knee, _thighSitQuatNeg);
            const zPos = scoreKneeForwardZ(upLeg, upLegRest, knee, _thighSitQuatPos);
            return zPos > zNeg ? _thighSitQuatPos : _thighSitQuatNeg;
          };

          const scoreFootPose = (kneeBone, kneeRest, thighBone, thighRest, thighDelta, kneeDelta, footBone) => {
            // Apply thigh first so knee transforms under it, then bend knee.
            if (thighRest) _tmpQuat.copy(thighRest).multiply(thighDelta);
            else _tmpQuat.copy(thighDelta);
            thighBone.quaternion.copy(_tmpQuat);
            if (kneeRest) _tmpQuat.copy(kneeRest).multiply(kneeDelta);
            else _tmpQuat.copy(kneeDelta);
            kneeBone.quaternion.copy(_tmpQuat);
            avatar.current.updateMatrixWorld(true);
            footBone.getWorldPosition(_tmpWorldPos);
            _tmpLocalPos.copy(_tmpWorldPos);
            group.current.worldToLocal(_tmpLocalPos);
            // Prefer foot forward (+Z) and down (-Y).
            return _tmpLocalPos.z - _tmpLocalPos.y * 0.25;
          };

          const pickKnee = (kneeBone, kneeRest, thighBone, thighRest, thighDelta, footBone, defaultDelta) => {
            if (!footBone) return defaultDelta;
            const sNeg = scoreFootPose(kneeBone, kneeRest, thighBone, thighRest, thighDelta, _kneeBendNeg, footBone);
            const sPos = scoreFootPose(kneeBone, kneeRest, thighBone, thighRest, thighDelta, _kneeBendPos, footBone);
            return sPos > sNeg ? _kneeBendPos : _kneeBendNeg;
          };

          const thighL = pickThigh(leftUpLegRef.current, leftUpLegRestRef.current, leftLegRef.current);
          const thighR = pickThigh(rightUpLegRef.current, rightUpLegRestRef.current, rightLegRef.current);
          const kneeL = pickKnee(leftLegRef.current, leftLegRestRef.current, leftUpLegRef.current, leftUpLegRestRef.current, thighL, leftFoot, _kneeBendNeg);
          const kneeR = pickKnee(rightLegRef.current, rightLegRestRef.current, rightUpLegRef.current, rightUpLegRestRef.current, thighR, rightFoot, _kneeBendPos);

          sitLegFixRef.current = { thighL, thighR, kneeL, kneeR };
        }

        const thighL = sitLegFixRef.current?.thighL || _thighSitQuatNeg;
        const thighR = sitLegFixRef.current?.thighR || _thighSitQuatNeg;
        const kneeL = sitLegFixRef.current?.kneeL || _kneeBendNeg;
        const kneeR = sitLegFixRef.current?.kneeR || _kneeBendPos;

        // Apply as delta from rest pose (prevents hips->leg flips on mirrored rigs).
        // Use the same sit deltas for both sides. With rest-pose deltas applied,
        // this avoids the common case where one knee bends the wrong way.
        if (leftUpLegRef.current) {
          if (leftUpLegRestRef.current) leftUpLegRef.current.quaternion.copy(leftUpLegRestRef.current).multiply(thighL);
          else leftUpLegRef.current.quaternion.copy(thighL);
        }
        if (rightUpLegRef.current) {
          if (rightUpLegRestRef.current) rightUpLegRef.current.quaternion.copy(rightUpLegRestRef.current).multiply(thighR);
          else rightUpLegRef.current.quaternion.copy(thighR);
        }
        if (leftLegRef.current) {
          if (leftLegRestRef.current) leftLegRef.current.quaternion.copy(leftLegRestRef.current).multiply(kneeL);
          else leftLegRef.current.quaternion.copy(kneeL);
        }
        if (rightLegRef.current) {
          if (rightLegRestRef.current) rightLegRef.current.quaternion.copy(rightLegRestRef.current).multiply(kneeR);
          else rightLegRef.current.quaternion.copy(kneeR);
        }
      }
    } else {
      const path = pathRef.current;
      const idx = pathIndexRef.current;
      if (idx < path.length) {
        const target = path[idx];
        const dist = group.current.position.distanceTo(target);

        if (dist > ARRIVAL_THRESHOLD) {
          _direction.copy(target).sub(group.current.position).normalize();
          _lookMatrix.lookAt(_direction, _zero, _up);
          _targetQuat.setFromRotationMatrix(_lookMatrix);
          group.current.quaternion.slerp(_targetQuat, Math.min(1, ROTATION_SPEED * delta));

          const isLastWaypoint = idx === path.length - 1;
          const speedScale = isLastWaypoint ? Math.max(0.3, Math.min(1, dist / 1.0)) : 1;
          const step = MOVEMENT_SPEED * speedScale * delta;
          const moveDistance = Math.min(step, dist);

          _direction.copy(target).sub(group.current.position).normalize().multiplyScalar(moveDistance);
          group.current.position.add(_direction);

          applyAnimation("M_Walk_001");
          isDancingRef.current = false;
          isWavingRef.current = false;
          idleTimeRef.current = 0;
          idleLookTargetRef.current = null;
          walkGraceRef.current = 0.15; // reset grace timer while walking

          // Footstep sounds — local player only, every ~350ms
          if (id === user) {
            footstepAccRef.current += delta;
            if (footstepAccRef.current >= 0.35) {
              footstepAccRef.current = 0;
              footstepVariantRef.current = (footstepVariantRef.current % 3) + 1;
              soundManager.play(`footstep_${footstepVariantRef.current}`);
            }
          }
        } else {
          group.current.position.copy(target);
          pathIndexRef.current++;

          // Check if path just completed and we should transition to sitting
          if (pathIndexRef.current >= path.length && walkToSitRef.current && seatDataRef.current) {
            walkToSitRef.current = false;
            isSittingRef.current = true;
          }

          // Keep walk animation active while there are more waypoints
          // so we don't flash idle for a frame between waypoints
          if (pathIndexRef.current < path.length) {
            applyAnimation("M_Walk_001");
            walkGraceRef.current = 0.15;
          }
        }
      } else if (walkGraceRef.current > 0) {
        // Grace period — hold walk animation briefly after path ends
        // so a new path from a quick re-click doesn't cause idle flash
        walkGraceRef.current -= delta;
      } else if (isWavingRef.current) {
        idleTimeRef.current = 0;
        idleLookTargetRef.current = null;
        if (waveTargetIdRef.current) {
          const targetObj = threeScene.getObjectByName(`character-${waveTargetIdRef.current}`);
          if (targetObj && group.current) {
            _direction.copy(targetObj.position).sub(group.current.position);
            _direction.y = 0;
            if (_direction.lengthSq() > 0.001) {
              _direction.normalize();
              _lookMatrix.lookAt(_direction, _zero, _up);
              _targetQuat.setFromRotationMatrix(_lookMatrix);
              group.current.quaternion.slerp(_targetQuat, Math.min(1, ROTATION_SPEED * delta));
            }
          }
        }
        applyAnimation("M_Standing_Expressions_001");
      } else {
        if (isDancingRef.current) {
          applyAnimation("M_Dances_001");
          idleTimeRef.current = 0;
        } else {
          applyAnimation("M_Standing_Idle_001");

          // Idle look-around: characters periodically glance in a new direction
          idleTimeRef.current += delta;
          if (idleTimeRef.current >= idleLookTimerRef.current) {
            // Pick a new random direction to glance toward
            const glanceAngle = initialRotationRef.current + (Math.random() - 0.5) * Math.PI * 0.8;
            _idleGlanceQuat.setFromAxisAngle(_up, glanceAngle);
            idleLookTargetRef.current = idleLookTargetRef.current || new THREE.Quaternion();
            idleLookTargetRef.current.copy(_idleGlanceQuat);
            idleTimeRef.current = 0;
            idleLookTimerRef.current = 3 + Math.random() * 6; // next glance in 3-9 seconds
          }

          // Smoothly rotate toward the idle glance target
          if (idleLookTargetRef.current) {
            group.current.quaternion.slerp(idleLookTargetRef.current, Math.min(1, 1.5 * delta));
          }
        }
      }
    }

    // Apply procedural animation for non-humanoid models
    if (isNonHumanoid && proceduralBonesRef.current) {
      proceduralTimeRef.current += delta;
      let procState = "idle";
      const anim = animationRef.current;
      if (anim === "M_Walk_001") procState = "walk";
      else if (anim === "M_Dances_001") procState = "dance";
      else if (anim === "M_Standing_Expressions_001") procState = "wave";
      else if (anim === "M_Sitting_001") procState = "sit";
      applyProceduralAnimation(procState, proceduralTimeRef.current, proceduralBonesRef.current, restPosesRef.current);
    }

    // Task 4: Throttle animation mixer for "mid" distance tier (4 fps)
    if (!isNonHumanoid && distanceTierRef.current === "mid" && mixer) {
      midAnimAccRef.current += delta;
      if (midAnimAccRef.current >= 0.25) {
        mixer.update(midAnimAccRef.current);
        midAnimAccRef.current = 0;
      }
      // Prevent drei's automatic mixer.update by setting timeScale to 0
      if (mixer.timeScale !== 0) mixer.timeScale = 0;
    } else if (!isNonHumanoid && mixer) {
      // Near tier: normal speed — flush any accumulated mid-tier time first
      if (mixer.timeScale !== 1) {
        if (midAnimAccRef.current > 0) {
          mixer.update(midAnimAccRef.current);
        }
        mixer.timeScale = 1;
        midAnimAccRef.current = 0;
      }
    }
  });

  const handleCharacterClick = useCallback((e) => {
    e.stopPropagation();
    setSelectedCharacter({ id, name, avatarUrl, isBot, position: group.current?.position });
  }, [id, name, avatarUrl, isBot, setSelectedCharacter]);

  const handleHoverWave = useCallback((e) => {
    e.stopPropagation();
    socket.emit("wave:at", id);
    setHovered(false);
  }, [id]);

  const handleHoverFollow = useCallback((e) => {
    e.stopPropagation();
    if (followedCharacter?.id === id) {
      setFollowedCharacter(null);
    } else {
      setFollowedCharacter({ id, name });
    }
    setHovered(false);
  }, [id, name, followedCharacter, setFollowedCharacter]);

  const handleHoverViewProfile = useCallback((e) => {
    e.stopPropagation();
    // Prefer the persistent userId; fall back to the ephemeral socket id
    // (only characters that predate the userId plumbing; still lets the
    // endpoint return a 404 gracefully instead of nothing happening).
    setProfileViewTarget(userId || id);
    setHovered(false);
  }, [id, userId, setProfileViewTarget]);

  return (
    <group
      ref={group}
      position={position}
      dispose={null}
      name={`character-${id}`}
      visible={true}
      onClick={handleCharacterClick}
      onPointerOver={() => { document.body.style.cursor = "pointer"; if (id !== user) setHovered(true); }}
      onPointerOut={() => { document.body.style.cursor = "auto"; setHovered(false); }}
    >
      {(showHtmlOverlay || id === user) && !leaving && (
        <>
          {/* Always-visible name label — clickable to open character menu */}
          <Html position-y={isNonHumanoid ? 1.1 : 2.1} center distanceFactor={8} zIndexRange={[1, 0]} style={{ overflow: 'visible', pointerEvents: 'none' }}>
            <div
              className="select-none cursor-pointer"
              style={{ pointerEvents: 'auto' }}
              onClick={(e) => {
                e.stopPropagation();
                setSelectedCharacter({ id, name, avatarUrl, isBot, position: group.current?.position });
              }}
            >
              <div className="flex flex-col items-center justify-center gap-0.5 whitespace-nowrap">
                {(() => {
                  const emotion = characterEmotions[id];
                  let moodEmoji = null;
                  if (emotion) {
                    moodEmoji = EMOTION_EMOJIS[emotion] || null;
                  }
                  // Fallback: bots get crab if no mood data
                  if (!moodEmoji && isBot) moodEmoji = '\u{1F980}';
                  return moodEmoji ? (
                    <span className="text-lg leading-none" style={{ filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.5))" }}>
                      {moodEmoji}
                    </span>
                  ) : null;
                })()}
                <span
                  className="text-[11px] font-bold px-2 py-0.5 rounded-full"
                  style={{
                    color: isBot ? "#93c5fd" : "#ffffff",
                    background: "rgba(0,0,0,0.45)",
                    backdropFilter: "blur(4px)",
                    textShadow: "0 1px 2px rgba(0,0,0,0.5)",
                  }}
                >
                  {name}
                </span>
              </div>
            </div>
          </Html>
          {/* Hover action buttons — between name and chat bubble */}
          {hovered && id !== user && (
            <Html position-y={isNonHumanoid ? 1.4 : 2.45} center distanceFactor={8} zIndexRange={[2, 0]} style={{ overflow: 'visible', pointerEvents: 'none' }}>
              <div
                className="flex items-center gap-1"
                style={{
                  pointerEvents: 'auto',
                  animation: 'fadeIn 150ms ease-out',
                }}
              >
                <button
                  onClick={handleHoverWave}
                  className="flex items-center gap-1 px-2 py-1 rounded-full text-[11px] font-medium text-white cursor-pointer transition-all hover:scale-105 active:scale-95"
                  style={{
                    background: 'rgba(0,0,0,0.55)',
                    backdropFilter: 'blur(4px)',
                    border: '1px solid rgba(255,255,255,0.15)',
                  }}
                >
                  <span>{"\u{1F44B}"}</span> Wave
                </button>
                <button
                  onClick={handleHoverFollow}
                  className="flex items-center gap-1 px-2 py-1 rounded-full text-[11px] font-medium text-white cursor-pointer transition-all hover:scale-105 active:scale-95"
                  style={{
                    background: followedCharacter?.id === id ? 'rgba(59,130,246,0.7)' : 'rgba(0,0,0,0.55)',
                    backdropFilter: 'blur(4px)',
                    border: '1px solid rgba(255,255,255,0.15)',
                  }}
                >
                  <span>{followedCharacter?.id === id ? "\u{1F441}\uFE0F" : "\u{1F4F7}"}</span> {followedCharacter?.id === id ? "Unfollow" : "Follow"}
                </button>
                <button
                  onClick={handleHoverViewProfile}
                  className="flex items-center gap-1 px-2 py-1 rounded-full text-[11px] font-medium text-white cursor-pointer transition-all hover:scale-105 active:scale-95"
                  style={{
                    background: 'rgba(0,0,0,0.55)',
                    backdropFilter: 'blur(4px)',
                    border: '1px solid rgba(255,255,255,0.15)',
                  }}
                  title="View profile"
                >
                  <span>{"\u{1F464}"}</span> Profile
                </button>
              </div>
            </Html>
          )}
          {/* Chat bubble + action status — positioned above name label */}
          <Html position-y={isNonHumanoid ? 1.7 : 2.8} center distanceFactor={8} zIndexRange={[1, 0]} style={{ overflow: 'visible', pointerEvents: 'none' }}>
            <div className="w-60 max-w-full pointer-events-none overflow-visible">
              {/* Action status indicator — hidden for bots to reduce visual noise */}
              {actionStatus && !showChatBubble && !isBot && (
                <div
                  className={`text-center mb-1 p-1.5 px-3 rounded-lg border transition-opacity duration-300 ${
                    actionStatus.action === "thinking"
                      ? "bg-yellow-100/80 border-yellow-300/40"
                      : actionStatus.action === "building"
                      ? "bg-orange-100/80 border-orange-300/40"
                      : actionStatus.action === "done"
                      ? "bg-green-100/80 border-green-300/40"
                      : "bg-blue-100/80 border-blue-300/40"
                  }`}
                >
                  <p className="text-xs text-gray-700 leading-snug whitespace-nowrap">
                    {actionStatus.action === "thinking" && "🤔 "}
                    {actionStatus.action === "building" && "🔨 "}
                    {actionStatus.action === "done" && "✅ "}
                    {actionStatus.action === "walking" && "🚶 "}
                    {actionStatus.action === "chatting" && "💬 "}
                    {actionStatus.action === "dancing" && "💃 "}
                    {actionStatus.action === "emoting" && "😊 "}
                    {actionStatus.detail}
                  </p>
                </div>
              )}
              {/* Chat bubble */}
              <div
                className={`text-center break-words p-2 px-4 rounded-xl bg-white/80 border border-white/20 transition-opacity duration-500 ${
                  showChatBubble ? "opacity-100" : "opacity-0"
                }`}
              >
                <p className="text-sm text-black leading-snug">{chatMessage}</p>
              </div>
            </div>
          </Html>
        </>
      )}
      {/* Bot thinking indicator */}
      {isBot && isThinking && !showChatBubble && (
        <Html position-y={isNonHumanoid ? 1.7 : 2.8} center distanceFactor={8} zIndexRange={[2, 0]} style={{ overflow: 'visible', pointerEvents: 'none' }}>
          <div className="flex items-center justify-center gap-1 p-2 px-4 rounded-xl bg-white/90 border border-indigo-200/40 shadow-sm">
            <span
              className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce"
              style={{ animationDelay: "0ms", animationDuration: "600ms" }}
            />
            <span
              className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce"
              style={{ animationDelay: "150ms", animationDuration: "600ms" }}
            />
            <span
              className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce"
              style={{ animationDelay: "300ms", animationDuration: "600ms" }}
            />
          </div>
        </Html>
      )}
      {/* Bond emote bubble */}
      {bondEmote && (
        <Html position-y={isNonHumanoid ? 1.7 : 2.8} center distanceFactor={8} zIndexRange={[2, 0]} style={{ overflow: 'visible', pointerEvents: 'none' }}>
          <div className="text-center p-2 px-4 rounded-xl bg-pink-100/90 border border-pink-200/40 animate-bounce whitespace-nowrap">
            <p className="text-sm text-pink-600 font-semibold">{bondEmote}</p>
          </div>
        </Html>
      )}
      {/* Floating hearts for bonded proximity */}
      {showBondHearts && id === user && (
        <Html position-y={2.5} center distanceFactor={8} zIndexRange={[1, 0]} style={{ overflow: 'visible', pointerEvents: 'none' }}>
          <div className="flex gap-1 animate-bounce" style={{ filter: "drop-shadow(0 1px 3px rgba(236,72,153,0.5))" }}>
            <span className="text-pink-400 text-sm">&#x2764;&#xFE0F;</span>
            <span className="text-pink-300 text-xs" style={{ animationDelay: "0.15s" }}>&#x2764;&#xFE0F;</span>
            <span className="text-pink-400 text-sm" style={{ animationDelay: "0.3s" }}>&#x2764;&#xFE0F;</span>
          </div>
        </Html>
      )}
      {/* Invisible click hitbox — skinned meshes don't raycast reliably */}
      <mesh position-y={0.9}>
        <capsuleGeometry args={[0.3, 1.0, 4, 8]} />
        <meshBasicMaterial transparent opacity={0} depthWrite={false} />
      </mesh>
      <motion.group
        initial={{
          y: 1.5,
          rotateY: Math.PI * 2,
          scale: 0,
        }}
        animate={leaving
          ? { y: 0.5, rotateY: Math.PI, scale: 0 }
          : { y: 0, rotateY: 0, scale: 1 }
        }
        transition={leaving
          ? { duration: 0.7, ease: "easeIn" }
          : { delay: entranceDelayRef.current, mass: 2, stiffness: 300, damping: 30 }
        }
      >
        {avatarUrl.startsWith("/") ? (
          <primitive object={clone} ref={avatar} scale={0.63} position-y={0.6} />
        ) : (
          <primitive object={clone} ref={avatar} />
        )}
      </motion.group>
    </group>
  );
});

// --- Avatar Portrait Renderer ---
// Renders a close-up face portrait of a character model off-screen
const avatarPortraitCache = {};

export const renderAvatarPortrait = (avatarUrl, callback) => {
  if (!avatarUrl) return;
  if (avatarPortraitCache[avatarUrl]) {
    callback(avatarPortraitCache[avatarUrl]);
    return;
  }

  const size = 256;
  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false });
  renderer.setSize(size, size);
  renderer.setPixelRatio(1);
  renderer.outputColorSpace = THREE.SRGBColorSpace;

  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0xe8e8e8);

  // Soft lighting for portrait
  scene.add(new THREE.AmbientLight(0xffffff, 1.2));
  const keyLight = new THREE.DirectionalLight(0xffffff, 0.8);
  keyLight.position.set(1, 1, 2);
  scene.add(keyLight);
  const fillLight = new THREE.DirectionalLight(0xffffff, 0.3);
  fillLight.position.set(-1, 0.5, 1);
  scene.add(fillLight);

  const camera = new THREE.PerspectiveCamera(35, 1, 0.01, 100);

  const loader = new GLTFLoader();
  loader.load(
    avatarUrl,
    (gltf) => {
      const model = gltf.scene;
      scene.add(model);

      const modelConfig = getModelConfig(avatarUrl);

      // Non-humanoid models keep default orientation (face is toward +Z)

      // Update matrices so bone world positions are correct
      model.updateMatrixWorld(true);

      let targetPos;
      let cameraDistance;

      if (modelConfig) {
        // Non-humanoid: use bounding box for reliable framing
        const box = new THREE.Box3().setFromObject(model);
        const size3 = box.getSize(new THREE.Vector3());
        const center = box.getCenter(new THREE.Vector3());
        // Target upper portion (face area)
        targetPos = new THREE.Vector3(center.x, center.y + size3.y * 0.15, center.z);
        // Pull back enough to see the whole upper body
        cameraDistance = Math.max(size3.x, size3.y, size3.z) * 1.5;
      } else {
        // Humanoid (RPM): find Head bone for precise framing
        let headBone = null;
        model.traverse((child) => {
          if (child.isBone && child.name === "Head") {
            headBone = child;
          }
        });

        if (headBone) {
          targetPos = new THREE.Vector3();
          headBone.getWorldPosition(targetPos);
          targetPos.y += 0.05;
          cameraDistance = 0.5;
        } else {
          const box = new THREE.Box3().setFromObject(model);
          const size3 = box.getSize(new THREE.Vector3());
          const center = box.getCenter(new THREE.Vector3());
          targetPos = new THREE.Vector3(center.x, center.y + size3.y * 0.25, center.z);
          cameraDistance = Math.max(size3.x, size3.y) * 0.8;
        }
      }

      // Position camera in front of the face
      camera.position.set(
        targetPos.x,
        targetPos.y,
        targetPos.z + cameraDistance
      );
      camera.lookAt(targetPos);

      renderer.render(scene, camera);
      const dataUrl = renderer.domElement.toDataURL();

      // Cleanup
      scene.remove(model);
      model.traverse((child) => {
        if (child.isMesh) {
          child.geometry?.dispose();
          if (Array.isArray(child.material)) child.material.forEach((m) => m.dispose());
          else child.material?.dispose();
        }
      });
      renderer.dispose();

      avatarPortraitCache[avatarUrl] = dataUrl;
      callback(dataUrl);
    },
    undefined,
    () => {
      renderer.dispose();
      callback(null);
    }
  );
};

const BOND_LEVEL_COUNT = 6;
const EMOTION_OPTIONS = [
  { value: "", label: "None" },
  { value: "happy", label: "Happy" },
  { value: "sad", label: "Sad" },
  { value: "angry", label: "Angry" },
  { value: "love", label: "Love" },
  { value: "surprised", label: "Surprised" },
  { value: "anxious", label: "Anxious" },
  { value: "disgusted", label: "Disgusted" },
  { value: "neutral", label: "Neutral" },
  { value: "playful", label: "Playful" },
  { value: "confident", label: "Confident" },
];

export const CharacterMenu = () => {
  const [selectedCharacter, setSelectedCharacter] = useAtom(selectedCharacterAtom);
  const [followedCharacter, setFollowedCharacter] = useAtom(followedCharacterAtom);
  const [, setDmPanelTarget] = useAtom(dmPanelTargetAtom);
  const [, setDmInboxOpen] = useAtom(dmInboxOpenAtom);
  const [user] = useAtom(userAtom);
  const [bonds] = useAtom(bondsAtom);
  const [characterEmotions, setCharacterEmotions] = useAtom(characterEmotionsAtom);
  const [portraitUrl, setPortraitUrl] = useState(null);
  const [portraitLoading, setPortraitLoading] = useState(false);
  const prevCharIdRef = useRef(null);

  // Query bond info when character menu opens
  useEffect(() => {
    if (!selectedCharacter?.name) return;
    socket.emit("bond:query", selectedCharacter.name);
  }, [selectedCharacter?.id]);

  // Render portrait when selected character changes
  useEffect(() => {
    if (!selectedCharacter?.avatarUrl) return;
    if (selectedCharacter.id === prevCharIdRef.current) return;
    prevCharIdRef.current = selectedCharacter.id;

    const url = selectedCharacter.avatarUrl;
    if (avatarPortraitCache[url]) {
      setPortraitUrl(avatarPortraitCache[url]);
      setPortraitLoading(false);
      return;
    }

    setPortraitUrl(null);
    setPortraitLoading(true);
    renderAvatarPortrait(url, (dataUrl) => {
      setPortraitUrl(dataUrl);
      setPortraitLoading(false);
    });
  }, [selectedCharacter?.id, selectedCharacter?.avatarUrl]);

  if (!selectedCharacter || selectedCharacter.id === user) return null;

  const isFollowing = followedCharacter?.id === selectedCharacter.id;
  const bond = selectedCharacter.name ? bonds[selectedCharacter.name] : null;
  const currentEmotion = characterEmotions[selectedCharacter.id] || "";

  const handleWave = () => {
    socket.emit("wave:at", selectedCharacter.id);
    setSelectedCharacter(null);
  };

  const handleFollow = () => {
    if (isFollowing) {
      setFollowedCharacter(null);
    } else {
      setFollowedCharacter({ id: selectedCharacter.id, name: selectedCharacter.name });
    }
    setSelectedCharacter(null);
  };

  const handleTalkTo = () => {
    setDmPanelTarget({ id: selectedCharacter.id, name: selectedCharacter.name, isBot: selectedCharacter.isBot, userId: selectedCharacter.userId });
    setDmInboxOpen(false);
    setSelectedCharacter(null);
  };

  const handleShop = () => {
    setDmPanelTarget({ id: selectedCharacter.id, name: selectedCharacter.name, isBot: selectedCharacter.isBot, userId: selectedCharacter.userId });
    setDmInboxOpen(false);
    // Set a brief delay then switch tab via a custom event
    setTimeout(() => window.dispatchEvent(new CustomEvent("dm-panel-tab", { detail: "shop" })), 100);
    setSelectedCharacter(null);
  };

  const handleBuildRequest = () => {
    socket.emit("requestBuild", selectedCharacter.id);
    setSelectedCharacter(null);
  };

  const handleBondEmote = (emote) => {
    socket.emit("bond:emote", { emote, targetId: selectedCharacter.id });
    setSelectedCharacter(null);
  };

  const handleClose = () => {
    setSelectedCharacter(null);
  };

  const handleEmotionChange = (event) => {
    const value = event.target.value;
    const id = selectedCharacter.id;
    setCharacterEmotions((prev) => {
      if (!value) {
        if (!(id in prev)) return prev;
        const { [id]: _, ...rest } = prev;
        return rest;
      }
      return { ...prev, [id]: value };
    });
  };

  return (
    <div className="fixed inset-0 z-[20] flex items-center justify-center">
      {/* Backdrop — click to close */}
      <div className="absolute inset-0 bg-black/30" onClick={handleClose} />

      <div className="relative pointer-events-auto bg-white/95 backdrop-blur-md rounded-2xl border border-gray-200 shadow-2xl min-w-[240px] max-w-[280px] overflow-hidden">
        {/* Avatar portrait — rendered from 3D model */}
        <div className="bg-gradient-to-br from-gray-50 to-gray-100 flex items-center justify-center py-5">
          <div className="w-20 h-20 rounded-full overflow-hidden bg-gray-200 border-2 border-gray-300 shadow-lg">
            {portraitUrl ? (
              <img
                src={portraitUrl}
                alt={selectedCharacter.name}
                className="w-full h-full object-cover"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center">
                {portraitLoading ? (
                  <div className="w-5 h-5 border-2 border-gray-300 border-t-gray-500 rounded-full animate-spin" />
                ) : (
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 text-gray-400">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                  </svg>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Name + badge */}
        <div className="text-center px-4 pt-3 pb-2">
          <p className="text-gray-900 font-semibold text-base">{selectedCharacter.name || "Player"}</p>
          {selectedCharacter.isBot &&
          selectedCharacter.id?.startsWith("3dworldbot-") ? (
            <span className="inline-flex items-center gap-1 mt-1 text-xs font-semibold px-2.5 py-0.5 rounded-full bg-orange-100 text-orange-600">
              3D World
            </span>
          ) : (
            <span className={`inline-block mt-1 text-xs font-semibold px-2.5 py-0.5 rounded-full ${
              selectedCharacter.isBot
                ? "bg-blue-100 text-blue-600"
                : "bg-green-100 text-green-600"
            }`}>
              {selectedCharacter.isBot ? "Bot" : "Player"}
            </span>
          )}
        </div>

        {/* Bond gauge */}
        {bond && (
          <div className="px-4 pb-2">
            <div className="flex items-center justify-between mb-1">
              <span className={`text-[10px] font-semibold ${bond.maxLevel ? "text-pink-500" : "text-gray-500"}`}>
                {bond.levelLabel}
              </span>
              <span className="text-[10px] text-gray-400">
                {bond.maxLevel ? "MAX" : `${bond.score}/${bond.nextThreshold}`}
              </span>
            </div>
            <div className="flex gap-0.5">
              {Array.from({ length: BOND_LEVEL_COUNT }, (_, i) => (
                <div
                  key={i}
                  className={`h-1.5 flex-1 rounded-full transition-colors ${
                    i <= bond.level
                      ? bond.maxLevel
                        ? "bg-pink-400"
                        : "bg-blue-400"
                      : "bg-gray-200"
                  }`}
                />
              ))}
            </div>
          </div>
        )}

        {/* Emotion (dev) */}
        <div className="px-4 pb-2">
          <label className="block text-[10px] font-semibold text-gray-500 mb-1">Emotion (dev)</label>
          <select
            value={currentEmotion}
            onChange={handleEmotionChange}
            className="w-full text-xs border border-gray-200 rounded-lg px-2 py-1 bg-white/80 text-gray-700"
          >
            {EMOTION_OPTIONS.map((opt) => (
              <option key={opt.value || "none"} value={opt.value}>{opt.label}</option>
            ))}
          </select>
        </div>

        {/* Actions */}
        <div className="flex items-end justify-center gap-1 px-3 py-3 bg-white/95 backdrop-blur-sm rounded-b-2xl border-t border-gray-100">
          <button
            onClick={handleWave}
            className="flex flex-col items-center gap-0.5 px-3 py-1.5 rounded-xl cursor-pointer hover:bg-gray-100 transition-colors group"
          >
            <span className="text-lg">{"\u{1F44B}"}</span>
            <span className="text-[10px] text-gray-500 group-hover:text-gray-800 font-medium transition-colors">Wave</span>
          </button>
          <button
            onClick={handleFollow}
            className={`flex flex-col items-center gap-0.5 px-3 py-1.5 rounded-xl cursor-pointer transition-colors group ${
              isFollowing ? "bg-blue-50" : "hover:bg-gray-100"
            }`}
          >
            <span className="text-lg">{isFollowing ? "\u{1F441}\uFE0F" : "\u{1F4F7}"}</span>
            <span className={`text-[10px] font-medium transition-colors ${
              isFollowing
                ? "text-blue-600"
                : "text-gray-500 group-hover:text-gray-800"
            }`}>{isFollowing ? "Unfollow" : "Follow"}</span>
          </button>
          {/* Bond-locked emotes — only show at max bond level */}
          {bond?.maxLevel && (
            <>
              <div className="w-px h-8 bg-pink-200" />
              <button
                onClick={() => handleBondEmote("highfive")}
                className="flex flex-col items-center gap-0.5 px-3 py-1.5 rounded-xl cursor-pointer hover:bg-pink-50 transition-colors group"
              >
                <span className="text-lg">{"\u{1F64F}"}</span>
                <span className="text-[10px] text-pink-400 group-hover:text-pink-600 font-medium transition-colors">Hi-Five</span>
              </button>
              <button
                onClick={() => handleBondEmote("hug")}
                className="flex flex-col items-center gap-0.5 px-3 py-1.5 rounded-xl cursor-pointer hover:bg-pink-50 transition-colors group"
              >
                <span className="text-lg">{"\u{1FAC2}"}</span>
                <span className="text-[10px] text-pink-400 group-hover:text-pink-600 font-medium transition-colors">Hug</span>
              </button>
            </>
          )}
          {selectedCharacter.isBot &&
            selectedCharacter.isOfficialBot &&
            !selectedCharacter.id?.startsWith("3dworldbot-") && (
            <>
              <div className="w-px h-8 bg-gray-200" />
              <button
                onClick={handleTalkTo}
                className="flex flex-col items-center gap-0.5 px-3 py-1.5 rounded-xl cursor-pointer hover:bg-indigo-50 transition-colors group"
              >
                <span className="text-lg">{"\u{1F4AC}"}</span>
                <span className="text-[10px] text-indigo-400 group-hover:text-indigo-600 font-medium transition-colors">Talk</span>
              </button>
              <button
                onClick={handleShop}
                className="flex flex-col items-center gap-0.5 px-3 py-1.5 rounded-xl cursor-pointer hover:bg-amber-50 transition-colors group"
              >
                <span className="text-lg">{"\u{1F6D2}"}</span>
                <span className="text-[10px] text-amber-500 group-hover:text-amber-700 font-medium transition-colors">Shop</span>
              </button>
              <button
                onClick={handleBuildRequest}
                className="flex flex-col items-center gap-0.5 px-3 py-1.5 rounded-xl cursor-pointer hover:bg-green-50 transition-colors group"
              >
                <span className="text-lg">{"\u{1F528}"}</span>
                <span className="text-[10px] text-green-500 group-hover:text-green-700 font-medium transition-colors">Build</span>
              </button>
            </>
          )}
        </div>

        {/* Close button */}
        <button
          onClick={handleClose}
          className="absolute top-2 right-2 text-gray-400 hover:text-gray-600 transition-colors w-7 h-7 flex items-center justify-center rounded-full bg-gray-200/50 hover:bg-gray-200"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  );
};

// Preload is handled dynamically per-avatar, no static preload needed
useGLTF.preload("/animations/M_Walk_001.glb");
useGLTF.preload("/animations/M_Standing_Idle_001.glb");
useGLTF.preload("/animations/M_Dances_001.glb");
useGLTF.preload("/animations/M_Standing_Expressions_001.glb");
useGLTF.preload("/animations/M_Sitting_001.glb");
