/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function TownHall(props) {
  const { nodes, materials } = useGLTF("/models/TownHall.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["building-n_1"].geometry}
        material={materials.colormap}
        castShadow
      />
    </group>
  );
}

useGLTF.preload("/models/TownHall.glb");
